// <auto-generated />
using System;
using DaLance.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DaLance.Entity.Migrations
{
    [DbContext(typeof(DaLanceContext))]
    [Migration("20210203055018_Init_Migrations")]
    partial class Init_Migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DaLance.Domain.Models.Lance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<DateTime>("data_alteracao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("produtoid")
                        .HasColumnType("integer");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.Property<int?>("usuarioid")
                        .HasColumnType("integer");

                    b.Property<double>("valor")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.HasIndex("produtoid");

                    b.HasIndex("usuarioid");

                    b.ToTable("lances");
                });

            modelBuilder.Entity("DaLance.Domain.Models.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<DateTime>("data_alteracao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.Property<double>("valor")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("produtos");
                });

            modelBuilder.Entity("DaLance.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<DateTime>("data_alteracao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idade")
                        .HasColumnType("integer");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("DaLance.Domain.Models.Lance", b =>
                {
                    b.HasOne("DaLance.Domain.Models.Produto", "produto")
                        .WithMany()
                        .HasForeignKey("produtoid");

                    b.HasOne("DaLance.Domain.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid");
                });
#pragma warning restore 612, 618
        }
    }
}
